worker_processes  auto;

events{
    worker_connections  8192;
}

http {

    upstream backend {
        least_conn;
        server phpswoole1:9502;
        server phpswoole2:9502;
        keepalive 120;
    }

    upstream websocket {
        server phpswoole1:9504;
        server phpswoole2:9504;
    }

    server {
        listen 80;

        server_name localhost;

        location / {
            proxy_pass http://backend;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_http_version 1.1;
            proxy_connect_timeout 120;
        }

        location /ws {
            proxy_pass http://phpswoole1:9504;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

    }
}